export const authActions = {
  SIGN_UP_START: "SIGN_UP_START",
  SIGN_UP_SUCCESS: "SIGN_UP_SUCCESS",
  CHECK_USER_SESSION: "CHECK_USER_SESSION",
  LOGOUT: "LOGOUT",
};

export const movieActions = {
  FETCH_MOVIES_START: "FETCH_MOVIES_START",
  FETCH_MOVIES_SUCCESS: "FETCH_MOVIES_SUCCESS",
};
